server:
  ip: 0.0.0.0
  port: 8082

cos:
  cosBucketAddr: https://netdisk-1304379399.cos.ap-beijing.myqcloud.com
  secretId: AKID3b4KXfhYCdtAJi4LWbeXEj196yDKGy0p
  secretKey: lKgpmW3kLkwvkMk05zgdS4TfcZSARUce

dataSource:
  sourceName: mysql
  username: root
  password: 2001823
  address: 127.0.0.1:3306
  database: netdisk